"""add alert lifecycle timestamps

Revision ID: 39f2aaeab9a0
Revises: 49eb18886b2b
Create Date: 2026-01-14 16:06:29.216390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f2aaeab9a0'
down_revision: Union[str, Sequence[str], None] = '49eb18886b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('first_seen_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'closed_at')
    op.drop_column('alerts', 'first_seen_at')
    # ### end Alembic commands ###
